# Generated by Django 2.2.20 on 2021-04-23 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKey",
        ),
    ]
