# Generated by Django 2.2.20 on 2021-05-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0003_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="django_fullctl.Organization",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.ContentType",
            ),
        ),
    ]
