# Generated by Django 2.2.20 on 2021-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0004_auto_20210528_1247"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="org_key",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user_key",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="key",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
