# Generated by Django 3.2.4 on 2021-08-05 12:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("django_fullctl", "0012_auto_20210805_1153"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CallCommandTask",
        ),
        migrations.CreateModel(
            name="CallCommand",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
