# Generated by Django 3.2.4 on 2021-08-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0014_alter_taskclaim_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="django_fullctl.task",
            ),
        ),
    ]
