# Generated by Django 3.2.4 on 2021-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0015_alter_task_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="limit_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
