# Generated by Django 3.2.17 on 2023-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0028_request_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
