# Generated by Django 4.2.10 on 2024-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0032_auto_20230719_1049"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="fullctl_tas_status_d88ee1_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["op"], name="fullctl_tas_op_ca48a6_idx"),
        ),
    ]
