# Generated by Django 4.2.15 on 2025-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fullctl", "0034_task_requeued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebridgeaction",
            name="function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
