# Generated by Django 4.2.16 on 2025-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fullctl", "0035_alter_servicebridgeaction_function"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created"], name="fullctl_tas_created_137d72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["queue_id"], name="fullctl_tas_queue_i_522107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("queue_id__isnull", True)),
                fields=["status", "-requeued", "created"],
                name="idx_poll_next_tasks",
            ),
        ),
    ]
