# Generated by Django 4.2.19 on 2025-04-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fullctl", "0036_task_fullctl_tas_created_137d72_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHeartbeat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeat",
                        to="django_fullctl.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Heartbeat",
                "verbose_name_plural": "Task Heartbeats",
                "db_table": "fullctl_task_heartbeat",
            },
        ),
    ]
