# Generated by Django 4.2.19 on 2025-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fullctl", "0037_taskheartbeat"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskheartbeat",
            index=models.Index(
                fields=["timestamp"], name="fullctl_tas_timesta_1a9e0d_idx"
            ),
        ),
    ]
