# Generated by Django 4.2.13 on 2025-05-14 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_fullctl", "0038_taskheartbeat_fullctl_tas_timesta_1a9e0d_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskScheduleClaim",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("worker_id", models.CharField(max_length=255)),
                ("schedule_date", models.DateTimeField()),
                (
                    "task_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_fullctl.taskschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Schedule Claim",
                "verbose_name_plural": "Task Schedule Claims",
                "db_table": "fullctl_task_schedule_claim",
                "unique_together": {("task_schedule", "schedule_date")},
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
